version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app1:
    build: .
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${LOCAL_MONGO_DB}
    depends_on:
      - redis

  app2:
    build: .
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${LOCAL_MONGO_DB}
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2